'''########################################################################
Basic tool for converting hentaigana unicode encoded characters to hiragana

The characters and codepoints are based on Unicode 10.0 specification and
comprise the characters in block U+1B000–U+1B0FF (Kana Supplement) and
block U+1B100–U+1B12F (Kana Extended-A).
Note that some hentaigana can be mapped to multiple corresponding kana.
In those cases the characters point to the first (and supposedly most used)
corresponding kana.
  eg. 𛀅 # HENTAIGANA LETTER A-WO (U+1B005) maps to あ (A) and not を (WO)
Characters are mapped using a plain dictionary so that it should be easy to
change any mappings according to one's use case.
Characters with multiple possible associations are marked with a (!) at the
end of the comment section.
'''########################################################################
chardict={
		'𛀀':'エ', # KATAKANA LETTER ARCHAIC E (U+1B000)
		'𛀁':'え', # HIRAGANA LETTER ARCHAIC YE (U+1B001)
		'𛀂':'あ', # HENTAIGANA LETTER A-1 (U+1B002)
		'𛀃':'あ', # HENTAIGANA LETTER A-2 (U+1B003)
		'𛀄':'あ', # HENTAIGANA LETTER A-3 (U+1B004)
		'𛀅':'あ', # HENTAIGANA LETTER A-WO (U+1B005) (!)
		'𛀆':'い', # HENTAIGANA LETTER I-1 (U+1B006)
		'𛀇':'い', # HENTAIGANA LETTER I-2 (U+1B007)
		'𛀈':'い', # HENTAIGANA LETTER I-3 (U+1B008)
		'𛀉':'い', # HENTAIGANA LETTER I-4 (U+1B009)
		'𛀊':'う', # HENTAIGANA LETTER U-1 (U+1B00A)
		'𛀋':'う', # HENTAIGANA LETTER U-2 (U+1B00B)
		'𛀌':'う', # HENTAIGANA LETTER U-3 (U+1B00C)
		'𛀍':'う', # HENTAIGANA LETTER U-4 (U+1B00D)
		'𛀎':'う', # HENTAIGANA LETTER U-5 (U+1B00E)
		'𛀏':'え', # HENTAIGANA LETTER E-2 (U+1B00F)
		'𛀐':'え', # HENTAIGANA LETTER E-3 (U+1B010)
		'𛀑':'え', # HENTAIGANA LETTER E-4 (U+1B011)
		'𛀒':'え', # HENTAIGANA LETTER E-5 (U+1B012)
		'𛀓':'え', # HENTAIGANA LETTER E-6 (U+1B013)
		'𛀔':'お', # HENTAIGANA LETTER O-1 (U+1B014)
		'𛀕':'お', # HENTAIGANA LETTER O-2 (U+1B015)
		'𛀖':'お', # HENTAIGANA LETTER O-3 (U+1B016)
		'𛀗':'か', # HENTAIGANA LETTER KA-1 (U+1B017)
		'𛀘':'か', # HENTAIGANA LETTER KA-2 (U+1B018)
		'𛀙':'か', # HENTAIGANA LETTER KA-3 (U+1B019)
		'𛀚':'か', # HENTAIGANA LETTER KA-4 (U+1B01A)
		'𛀛':'か', # HENTAIGANA LETTER KA-5 (U+1B01B)
		'𛀜':'か', # HENTAIGANA LETTER KA-6 (U+1B01C)
		'𛀝':'か', # HENTAIGANA LETTER KA-7 (U+1B01D)
		'𛀞':'か', # HENTAIGANA LETTER KA-8 (U+1B01E)
		'𛀟':'か', # HENTAIGANA LETTER KA-9 (U+1B01F)
		'𛀠':'か', # HENTAIGANA LETTER KA-10 (U+1B020)
		'𛀡':'か', # HENTAIGANA LETTER KA-11 (U+1B021)
		'𛀢':'か', # HENTAIGANA LETTER KA-KE (U+1B022) (!)
		'𛀣':'き', # HENTAIGANA LETTER KI-1 (U+1B023)
		'𛀤':'き', # HENTAIGANA LETTER KI-2 (U+1B024)
		'𛀥':'き', # HENTAIGANA LETTER KI-3 (U+1B025)
		'𛀦':'き', # HENTAIGANA LETTER KI-4 (U+1B026)
		'𛀧':'き', # HENTAIGANA LETTER KI-5 (U+1B027)
		'𛀨':'き', # HENTAIGANA LETTER KI-6 (U+1B028)
		'𛀩':'き', # HENTAIGANA LETTER KI-7 (U+1B029)
		'𛀪':'き', # HENTAIGANA LETTER KI-8 (U+1B02A)
		'𛀫':'く', # HENTAIGANA LETTER KU-1 (U+1B02B)
		'𛀬':'く', # HENTAIGANA LETTER KU-2 (U+1B02C)
		'𛀭':'く', # HENTAIGANA LETTER KU-3 (U+1B02D)
		'𛀮':'く', # HENTAIGANA LETTER KU-4 (U+1B02E)
		'𛀯':'く', # HENTAIGANA LETTER KU-5 (U+1B02F)
		'𛀰':'く', # HENTAIGANA LETTER KU-6 (U+1B030)
		'𛀱':'く', # HENTAIGANA LETTER KU-7 (U+1B031)
		'𛀲':'け', # HENTAIGANA LETTER KE-1 (U+1B032)
		'𛀳':'け', # HENTAIGANA LETTER KE-2 (U+1B033)
		'𛀴':'け', # HENTAIGANA LETTER KE-3 (U+1B034)
		'𛀵':'け', # HENTAIGANA LETTER KE-4 (U+1B035)
		'𛀶':'け', # HENTAIGANA LETTER KE-5 (U+1B036)
		'𛀷':'け', # HENTAIGANA LETTER KE-6 (U+1B037)
		'𛀸':'こ', # HENTAIGANA LETTER KO-1 (U+1B038)
		'𛀹':'こ', # HENTAIGANA LETTER KO-2 (U+1B039)
		'𛀺':'こ', # HENTAIGANA LETTER KO-3 (U+1B03A)
		'𛀻':'こ', # HENTAIGANA LETTER KO-KI (U+1B03B) (!)
		'𛀼':'さ', # HENTAIGANA LETTER SA-1 (U+1B03C)
		'𛀽':'さ', # HENTAIGANA LETTER SA-2 (U+1B03D)
		'𛀾':'さ', # HENTAIGANA LETTER SA-3 (U+1B03E)
		'𛀿':'さ', # HENTAIGANA LETTER SA-4 (U+1B03F)
		'𛁀':'さ', # HENTAIGANA LETTER SA-5 (U+1B040)
		'𛁁':'さ', # HENTAIGANA LETTER SA-6 (U+1B041)
		'𛁂':'さ', # HENTAIGANA LETTER SA-7 (U+1B042)
		'𛁃':'さ', # HENTAIGANA LETTER SA-8 (U+1B043)
		'𛁄':'し', # HENTAIGANA LETTER SI-1 (U+1B044)
		'𛁅':'し', # HENTAIGANA LETTER SI-2 (U+1B045)
		'𛁆':'し', # HENTAIGANA LETTER SI-3 (U+1B046)
		'𛁇':'し', # HENTAIGANA LETTER SI-4 (U+1B047)
		'𛁈':'し', # HENTAIGANA LETTER SI-5 (U+1B048)
		'𛁉':'し', # HENTAIGANA LETTER SI-6 (U+1B049)
		'𛁊':'す', # HENTAIGANA LETTER SU-1 (U+1B04A)
		'𛁋':'す', # HENTAIGANA LETTER SU-2 (U+1B04B)
		'𛁌':'す', # HENTAIGANA LETTER SU-3 (U+1B04C)
		'𛁍':'す', # HENTAIGANA LETTER SU-4 (U+1B04D)
		'𛁎':'す', # HENTAIGANA LETTER SU-5 (U+1B04E)
		'𛁏':'す', # HENTAIGANA LETTER SU-6 (U+1B04F)
		'𛁐':'す', # HENTAIGANA LETTER SU-7 (U+1B050)
		'𛁑':'す', # HENTAIGANA LETTER SU-8 (U+1B051)
		'𛁒':'せ', # HENTAIGANA LETTER SE-1 (U+1B052)
		'𛁓':'せ', # HENTAIGANA LETTER SE-2 (U+1B053)
		'𛁔':'せ', # HENTAIGANA LETTER SE-3 (U+1B054)
		'𛁕':'せ', # HENTAIGANA LETTER SE-4 (U+1B055)
		'𛁖':'せ', # HENTAIGANA LETTER SE-5 (U+1B056)
		'𛁗':'そ', # HENTAIGANA LETTER SO-1 (U+1B057)
		'𛁘':'そ', # HENTAIGANA LETTER SO-2 (U+1B058)
		'𛁙':'そ', # HENTAIGANA LETTER SO-3 (U+1B059)
		'𛁚':'そ', # HENTAIGANA LETTER SO-4 (U+1B05A)
		'𛁛':'そ', # HENTAIGANA LETTER SO-5 (U+1B05B)
		'𛁜':'そ', # HENTAIGANA LETTER SO-6 (U+1B05C)
		'𛁝':'そ', # HENTAIGANA LETTER SO-7 (U+1B05D)
		'𛁞':'た', # HENTAIGANA LETTER TA-1 (U+1B05E)
		'𛁟':'た', # HENTAIGANA LETTER TA-2 (U+1B05F)
		'𛁠':'た', # HENTAIGANA LETTER TA-3 (U+1B060)
		'𛁡':'た', # HENTAIGANA LETTER TA-4 (U+1B061)
		'𛁢':'ち', # HENTAIGANA LETTER TI-1 (U+1B062)
		'𛁣':'ち', # HENTAIGANA LETTER TI-2 (U+1B063)
		'𛁤':'ち', # HENTAIGANA LETTER TI-3 (U+1B064)
		'𛁥':'ち', # HENTAIGANA LETTER TI-4 (U+1B065)
		'𛁦':'ち', # HENTAIGANA LETTER TI-5 (U+1B066)
		'𛁧':'ち', # HENTAIGANA LETTER TI-6 (U+1B067)
		'𛁨':'ち', # HENTAIGANA LETTER TI-7 (U+1B068)
		'𛁩':'つ', # HENTAIGANA LETTER TU-1 (U+1B069)
		'𛁪':'つ', # HENTAIGANA LETTER TU-2 (U+1B06A)
		'𛁫':'つ', # HENTAIGANA LETTER TU-3 (U+1B06B)
		'𛁬':'つ', # HENTAIGANA LETTER TU-4 (U+1B06C)
		'𛁭':'つ', # HENTAIGANA LETTER TU-TO (U+1B06D) (!)
		'𛁮':'て', # HENTAIGANA LETTER TE-1 (U+1B06E)
		'𛁯':'て', # HENTAIGANA LETTER TE-2 (U+1B06F)
		'𛁰':'て', # HENTAIGANA LETTER TE-3 (U+1B070)
		'𛁱':'て', # HENTAIGANA LETTER TE-4 (U+1B071)
		'𛁲':'て', # HENTAIGANA LETTER TE-5 (U+1B072)
		'𛁳':'て', # HENTAIGANA LETTER TE-6 (U+1B073)
		'𛁴':'て', # HENTAIGANA LETTER TE-7 (U+1B074)
		'𛁵':'て', # HENTAIGANA LETTER TE-8 (U+1B075)
		'𛁶':'て', # HENTAIGANA LETTER TE-9 (U+1B076)
		'𛁷':'と', # HENTAIGANA LETTER TO-1 (U+1B077)
		'𛁸':'と', # HENTAIGANA LETTER TO-2 (U+1B078)
		'𛁹':'と', # HENTAIGANA LETTER TO-3 (U+1B079)
		'𛁺':'と', # HENTAIGANA LETTER TO-4 (U+1B07A)
		'𛁻':'と', # HENTAIGANA LETTER TO-5 (U+1B07B)
		'𛁼':'と', # HENTAIGANA LETTER TO-6 (U+1B07C)
		'𛁽':'と', # HENTAIGANA LETTER TO-RA (U+1B07D) (!)
		'𛁾':'な', # HENTAIGANA LETTER NA-1 (U+1B07E)
		'𛁿':'な', # HENTAIGANA LETTER NA-2 (U+1B07F)
		'𛂀':'な', # HENTAIGANA LETTER NA-3 (U+1B080)
		'𛂁':'な', # HENTAIGANA LETTER NA-4 (U+1B081)
		'𛂂':'な', # HENTAIGANA LETTER NA-5 (U+1B082)
		'𛂃':'な', # HENTAIGANA LETTER NA-6 (U+1B083)
		'𛂄':'な', # HENTAIGANA LETTER NA-7 (U+1B084)
		'𛂅':'な', # HENTAIGANA LETTER NA-8 (U+1B085)
		'𛂆':'な', # HENTAIGANA LETTER NA-9 (U+1B086)
		'𛂇':'に', # HENTAIGANA LETTER NI-1 (U+1B087)
		'𛂈':'に', # HENTAIGANA LETTER NI-2 (U+1B088)
		'𛂉':'に', # HENTAIGANA LETTER NI-3 (U+1B089)
		'𛂊':'に', # HENTAIGANA LETTER NI-4 (U+1B08A)
		'𛂋':'に', # HENTAIGANA LETTER NI-5 (U+1B08B)
		'𛂌':'に', # HENTAIGANA LETTER NI-6 (U+1B08C)
		'𛂍':'に', # HENTAIGANA LETTER NI-7 (U+1B08D)
		'𛂎':'に', # HENTAIGANA LETTER NI-TE (U+1B08E) (!)
		'𛂏':'ぬ', # HENTAIGANA LETTER NU-1 (U+1B08F)
		'𛂐':'ぬ', # HENTAIGANA LETTER NU-2 (U+1B090)
		'𛂑':'ぬ', # HENTAIGANA LETTER NU-3 (U+1B091)
		'𛂒':'ね', # HENTAIGANA LETTER NE-1 (U+1B092)
		'𛂓':'ね', # HENTAIGANA LETTER NE-2 (U+1B093)
		'𛂔':'ね', # HENTAIGANA LETTER NE-3 (U+1B094)
		'𛂕':'ね', # HENTAIGANA LETTER NE-4 (U+1B095)
		'𛂖':'ね', # HENTAIGANA LETTER NE-5 (U+1B096)
		'𛂗':'ね', # HENTAIGANA LETTER NE-6 (U+1B097)
		'𛂘':'ね', # HENTAIGANA LETTER NE-KO (U+1B098) (!)
		'𛂙':'の', # HENTAIGANA LETTER NO-1 (U+1B099)
		'𛂚':'の', # HENTAIGANA LETTER NO-2 (U+1B09A)
		'𛂛':'の', # HENTAIGANA LETTER NO-3 (U+1B09B)
		'𛂜':'の', # HENTAIGANA LETTER NO-4 (U+1B09C)
		'𛂝':'の', # HENTAIGANA LETTER NO-5 (U+1B09D)
		'𛂞':'は', # HENTAIGANA LETTER HA-1 (U+1B09E)
		'𛂟':'は', # HENTAIGANA LETTER HA-2 (U+1B09F)
		'𛂠':'は', # HENTAIGANA LETTER HA-3 (U+1B0A0)
		'𛂡':'は', # HENTAIGANA LETTER HA-4 (U+1B0A1)
		'𛂢':'は', # HENTAIGANA LETTER HA-5 (U+1B0A2)
		'𛂣':'は', # HENTAIGANA LETTER HA-6 (U+1B0A3)
		'𛂤':'は', # HENTAIGANA LETTER HA-7 (U+1B0A4)
		'𛂥':'は', # HENTAIGANA LETTER HA-8 (U+1B0A5)
		'𛂦':'は', # HENTAIGANA LETTER HA-9 (U+1B0A6)
		'𛂧':'は', # HENTAIGANA LETTER HA-10 (U+1B0A7)
		'𛂨':'は', # HENTAIGANA LETTER HA-11 (U+1B0A8)
		'𛂩':'ひ', # HENTAIGANA LETTER HI-1 (U+1B0A9)
		'𛂪':'ひ', # HENTAIGANA LETTER HI-2 (U+1B0AA)
		'𛂫':'ひ', # HENTAIGANA LETTER HI-3 (U+1B0AB)
		'𛂬':'ひ', # HENTAIGANA LETTER HI-4 (U+1B0AC)
		'𛂭':'ひ', # HENTAIGANA LETTER HI-5 (U+1B0AD)
		'𛂮':'ひ', # HENTAIGANA LETTER HI-6 (U+1B0AE)
		'𛂯':'ひ', # HENTAIGANA LETTER HI-7 (U+1B0AF)
		'𛂰':'ふ', # HENTAIGANA LETTER HU-1 (U+1B0B0)
		'𛂱':'ふ', # HENTAIGANA LETTER HU-2 (U+1B0B1)
		'𛂲':'ふ', # HENTAIGANA LETTER HU-3 (U+1B0B2)
		'𛂳':'へ', # HENTAIGANA LETTER HE-1 (U+1B0B3)
		'𛂴':'へ', # HENTAIGANA LETTER HE-2 (U+1B0B4)
		'𛂵':'へ', # HENTAIGANA LETTER HE-3 (U+1B0B5)
		'𛂶':'へ', # HENTAIGANA LETTER HE-4 (U+1B0B6)
		'𛂷':'へ', # HENTAIGANA LETTER HE-5 (U+1B0B7)
		'𛂸':'へ', # HENTAIGANA LETTER HE-6 (U+1B0B8)
		'𛂹':'へ', # HENTAIGANA LETTER HE-7 (U+1B0B9)
		'𛂺':'ほ', # HENTAIGANA LETTER HO-1 (U+1B0BA)
		'𛂻':'ほ', # HENTAIGANA LETTER HO-2 (U+1B0BB)
		'𛂼':'ほ', # HENTAIGANA LETTER HO-3 (U+1B0BC)
		'𛂽':'ほ', # HENTAIGANA LETTER HO-4 (U+1B0BD)
		'𛂾':'ほ', # HENTAIGANA LETTER HO-5 (U+1B0BE)
		'𛂿':'ほ', # HENTAIGANA LETTER HO-6 (U+1B0BF)
		'𛃀':'ほ', # HENTAIGANA LETTER HO-7 (U+1B0C0)
		'𛃁':'ほ', # HENTAIGANA LETTER HO-8 (U+1B0C1)
		'𛃂':'ま', # HENTAIGANA LETTER MA-1 (U+1B0C2)
		'𛃃':'ま', # HENTAIGANA LETTER MA-2 (U+1B0C3)
		'𛃄':'ま', # HENTAIGANA LETTER MA-3 (U+1B0C4)
		'𛃅':'ま', # HENTAIGANA LETTER MA-4 (U+1B0C5)
		'𛃆':'ま', # HENTAIGANA LETTER MA-5 (U+1B0C6)
		'𛃇':'ま', # HENTAIGANA LETTER MA-6 (U+1B0C7)
		'𛃈':'ま', # HENTAIGANA LETTER MA-7 (U+1B0C8)
		'𛃉':'み', # HENTAIGANA LETTER MI-1 (U+1B0C9)
		'𛃊':'み', # HENTAIGANA LETTER MI-2 (U+1B0CA)
		'𛃋':'み', # HENTAIGANA LETTER MI-3 (U+1B0CB)
		'𛃌':'み', # HENTAIGANA LETTER MI-4 (U+1B0CC)
		'𛃍':'み', # HENTAIGANA LETTER MI-5 (U+1B0CD)
		'𛃎':'み', # HENTAIGANA LETTER MI-6 (U+1B0CE)
		'𛃏':'み', # HENTAIGANA LETTER MI-7 (U+1B0CF)
		'𛃐':'む', # HENTAIGANA LETTER MU-1 (U+1B0D0)
		'𛃑':'む', # HENTAIGANA LETTER MU-2 (U+1B0D1)
		'𛃒':'む', # HENTAIGANA LETTER MU-3 (U+1B0D2)
		'𛃓':'む', # HENTAIGANA LETTER MU-4 (U+1B0D3)
		'𛃔':'め', # HENTAIGANA LETTER ME-1 (U+1B0D4)
		'𛃕':'め', # HENTAIGANA LETTER ME-2 (U+1B0D5)
		'𛃖':'め', # HENTAIGANA LETTER ME-MA (U+1B0D6) (!)
		'𛃗':'も', # HENTAIGANA LETTER MO-1 (U+1B0D7)
		'𛃘':'も', # HENTAIGANA LETTER MO-2 (U+1B0D8)
		'𛃙':'も', # HENTAIGANA LETTER MO-3 (U+1B0D9)
		'𛃚':'も', # HENTAIGANA LETTER MO-4 (U+1B0DA)
		'𛃛':'も', # HENTAIGANA LETTER MO-5 (U+1B0DB)
		'𛃜':'も', # HENTAIGANA LETTER MO-6 (U+1B0DC)
		'𛃝':'や', # HENTAIGANA LETTER YA-1 (U+1B0DD)
		'𛃞':'や', # HENTAIGANA LETTER YA-2 (U+1B0DE)
		'𛃟':'や', # HENTAIGANA LETTER YA-3 (U+1B0DF)
		'𛃠':'や', # HENTAIGANA LETTER YA-4 (U+1B0E0)
		'𛃡':'や', # HENTAIGANA LETTER YA-5 (U+1B0E1)
		'𛃢':'や', # HENTAIGANA LETTER YA-YO (U+1B0E2) (!)
		'𛃣':'ゆ', # HENTAIGANA LETTER YU-1 (U+1B0E3)
		'𛃤':'ゆ', # HENTAIGANA LETTER YU-2 (U+1B0E4)
		'𛃥':'ゆ', # HENTAIGANA LETTER YU-3 (U+1B0E5)
		'𛃦':'ゆ', # HENTAIGANA LETTER YU-4 (U+1B0E6)
		'𛃧':'よ', # HENTAIGANA LETTER YO-1 (U+1B0E7)
		'𛃨':'よ', # HENTAIGANA LETTER YO-2 (U+1B0E8)
		'𛃩':'よ', # HENTAIGANA LETTER YO-3 (U+1B0E9)
		'𛃪':'よ', # HENTAIGANA LETTER YO-4 (U+1B0EA)
		'𛃫':'よ', # HENTAIGANA LETTER YO-5 (U+1B0EB)
		'𛃬':'よ', # HENTAIGANA LETTER YO-6 (U+1B0EC)
		'𛃭':'ら', # HENTAIGANA LETTER RA-1 (U+1B0ED)
		'𛃮':'ら', # HENTAIGANA LETTER RA-2 (U+1B0EE)
		'𛃯':'ら', # HENTAIGANA LETTER RA-3 (U+1B0EF)
		'𛃰':'ら', # HENTAIGANA LETTER RA-4 (U+1B0F0)
		'𛃱':'り', # HENTAIGANA LETTER RI-1 (U+1B0F1)
		'𛃲':'り', # HENTAIGANA LETTER RI-2 (U+1B0F2)
		'𛃳':'り', # HENTAIGANA LETTER RI-3 (U+1B0F3)
		'𛃴':'り', # HENTAIGANA LETTER RI-4 (U+1B0F4)
		'𛃵':'り', # HENTAIGANA LETTER RI-5 (U+1B0F5)
		'𛃶':'り', # HENTAIGANA LETTER RI-6 (U+1B0F6)
		'𛃷':'り', # HENTAIGANA LETTER RI-7 (U+1B0F7)
		'𛃸':'る', # HENTAIGANA LETTER RU-1 (U+1B0F8)
		'𛃹':'る', # HENTAIGANA LETTER RU-2 (U+1B0F9)
		'𛃺':'る', # HENTAIGANA LETTER RU-3 (U+1B0FA)
		'𛃻':'る', # HENTAIGANA LETTER RU-4 (U+1B0FB)
		'𛃼':'る', # HENTAIGANA LETTER RU-5 (U+1B0FC)
		'𛃽':'る', # HENTAIGANA LETTER RU-6 (U+1B0FD)
		'𛃾':'れ', # HENTAIGANA LETTER RE-1 (U+1B0FE)
		'𛃿':'れ', # HENTAIGANA LETTER RE-2 (U+1B0FF)
		'𛄀':'れ', # HENTAIGANA LETTER RE-3 (U+1B100)
		'𛄁':'れ', # HENTAIGANA LETTER RE-4 (U+1B101)
		'𛄂':'ろ', # HENTAIGANA LETTER RO-1 (U+1B102)
		'𛄃':'ろ', # HENTAIGANA LETTER RO-2 (U+1B103)
		'𛄄':'ろ', # HENTAIGANA LETTER RO-3 (U+1B104)
		'𛄅':'ろ', # HENTAIGANA LETTER RO-4 (U+1B105)
		'𛄆':'ろ', # HENTAIGANA LETTER RO-5 (U+1B106)
		'𛄇':'ろ', # HENTAIGANA LETTER RO-6 (U+1B107)
		'𛄈':'わ', # HENTAIGANA LETTER WA-1 (U+1B108)
		'𛄉':'わ', # HENTAIGANA LETTER WA-2 (U+1B109)
		'𛄊':'わ', # HENTAIGANA LETTER WA-3 (U+1B10A)
		'𛄋':'わ', # HENTAIGANA LETTER WA-4 (U+1B10B)
		'𛄌':'わ', # HENTAIGANA LETTER WA-5 (U+1B10C)
		'𛄍':'ゐ', # HENTAIGANA LETTER WI-1 (U+1B10D)
		'𛄎':'ゐ', # HENTAIGANA LETTER WI-2 (U+1B10E)
		'𛄏':'ゐ', # HENTAIGANA LETTER WI-3 (U+1B10F)
		'𛄐':'ゐ', # HENTAIGANA LETTER WI-4 (U+1B110)
		'𛄑':'ゐ', # HENTAIGANA LETTER WI-5 (U+1B111)
		'𛄒':'ゑ', # HENTAIGANA LETTER WE-1 (U+1B112)
		'𛄓':'ゑ', # HENTAIGANA LETTER WE-2 (U+1B113)
		'𛄔':'ゑ', # HENTAIGANA LETTER WE-3 (U+1B114)
		'𛄕':'ゑ', # HENTAIGANA LETTER WE-4 (U+1B115)
		'𛄖':'を', # HENTAIGANA LETTER WO-1 (U+1B116)
		'𛄗':'を', # HENTAIGANA LETTER WO-2 (U+1B117)
		'𛄘':'を', # HENTAIGANA LETTER WO-3 (U+1B118)
		'𛄙':'を', # HENTAIGANA LETTER WO-4 (U+1B119)
		'𛄚':'を', # HENTAIGANA LETTER WO-5 (U+1B11A)
		'𛄛':'を', # HENTAIGANA LETTER WO-6 (U+1B11B)
		'𛄜':'を', # HENTAIGANA LETTER WO-7 (U+1B11C)
		'𛄝':'ん', # HENTAIGANA LETTER N-MU-MO-1 (U+1B11D) (!)
		'𛄞':'ん', # HENTAIGANA LETTER N-MU-MO-2 (U+1B11E) (!)
	}

# Function for converting a single hentaigana character to kana
def hentai_to_kana (character):
	if character in chardict:
		return (chardict[character])

# Sample usage of character substitution for a string using regular expressions
# Credit to Max Shawabkeh https://stackoverflow.com/a/2400577/8049293
import re
string='𛄚𛄆𛂘𛃮'
pattern = re.compile('|'.join(chardict.keys()))
result = pattern.sub(lambda x: chardict[x.group()], string)
print (result)